import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import assert from "node:assert";

// Set test environment so db.ts uses :memory: database
process.env.NODE_ENV = "test";

import { ProviderRegistry } from "../providers/ProviderRegistry.js";
import { RunRepository, MessageRepository } from "../database/repositories.js";
import { Orchestrator } from "./Orchestrator.js";
import { eventBus } from "./eventBus.js";
import type { Run, RunStatus } from "@bridgemind/shared";

// Mock config content
const mockConfig = {
  providers: {
    "test-planner": {
      type: "openai-compatible",
      displayName: "Test Planner Provider",
      baseUrl: "http://localhost:9999/planner",
      apiKey: "mock-key",
      models: ["model-plan"]
    },
    "test-coder": {
      type: "openai-compatible",
      displayName: "Test Coder Provider",
      baseUrl: "http://localhost:9999/coder",
      apiKey: "mock-key",
      models: ["model-code"]
    }
  }
};

test("Orchestrator Loop Integration Tests", async (t) => {
  const testConfigPath = path.join(process.cwd(), "providers.orch-test.json");
  fs.writeFileSync(testConfigPath, JSON.stringify(mockConfig, null, 2));

  t.after(() => {
    if (fs.existsSync(testConfigPath)) {
      fs.unlinkSync(testConfigPath);
    }
  });

  const originalFetch = globalThis.fetch;
  t.afterEach(() => {
    globalThis.fetch = originalFetch;
  });

  await t.test("Orchestrator - runs full loop and halts on FINAL_ACCEPTED", async () => {
    const registry = new ProviderRegistry(testConfigPath);
    const runRepo = new RunRepository();
    const messageRepo = new MessageRepository();
    const orchestrator = new Orchestrator(runRepo, messageRepo, registry);

    const runId = "run-test-123";
    const runData: Run = {
      id: runId,
      title: "Test Task",
      task: "Test building a greeting script",
      status: "created",
      plannerProviderId: "test-planner",
      plannerProviderDisplayName: "Test Planner Provider",
      plannerModel: "model-plan",
      coderProviderId: "test-coder",
      coderProviderDisplayName: "Test Coder Provider",
      coderModel: "model-code",
      maxRounds: 3,
      currentRound: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };

    runRepo.create(runData);

    // Track status transitions via eventBus
    const statusesEmitted: RunStatus[] = [];
    const eventListener = (event: any) => {
      if (event.type === "status_changed") {
        statusesEmitted.push(event.status);
      }
    };
    eventBus.on(`run:${runId}`, eventListener);
    t.after(() => {
      eventBus.off(`run:${runId}`, eventListener);
    });

    let roundCounter = 0;

    // Mock fetch to simulate Planner and Coder responses
    globalThis.fetch = async (url: any, options: any) => {
      const body = JSON.parse(options.body);
      const messages = body.messages || [];
      const systemPrompt = body.system || "";
      const lastMessage = messages[messages.length - 1]?.content || "";

      // 1. Planning phase
      if (url.includes("/planner") && lastMessage.includes("User Task:")) {
        return {
          ok: true,
          json: async () => ({
            choices: [{ message: { role: "assistant", content: "PLAN: 1. Console log hello" } }]
          })
        } as any;
      }

      // 2. Coder implementation / fixing phase
      if (url.includes("/coder")) {
        return {
          ok: true,
          json: async () => ({
            choices: [{ message: { role: "assistant", content: "console.log('hello');" } }]
          })
        } as any;
      }

      // 3. Reviewer phase
      if (url.includes("/planner") && lastMessage.includes("generated by the Coder")) {
        roundCounter++;
        // Round 1 rejects, Round 2 accepts
        const content = roundCounter === 1 
          ? "CHANGES_REQUIRED: missing semicolon or similar" 
          : "FINAL_ACCEPTED: looks perfect!";

        return {
          ok: true,
          json: async () => ({
            choices: [{ message: { role: "assistant", content } }]
          })
        } as any;
      }

      throw new Error(`Unexpected fetch URL in test: ${url}`);
    };

    // Trigger run execution synchronously
    await orchestrator.run(runId);

    // Verify database record has done status and final output code
    const finishedRun = runRepo.getById(runId);
    assert.ok(finishedRun);
    assert.strictEqual(finishedRun.status, "done");
    assert.strictEqual(finishedRun.finalOutput, "console.log('hello');");
    assert.strictEqual(finishedRun.currentRound, 2);

    // Verify messages saved
    const savedMsgs = messageRepo.listByRunId(runId);
    // Expected messages: Planner plan (1), Coder R1 (2), Reviewer R1 (3), Coder R2 (4), Reviewer R2 (5)
    assert.strictEqual(savedMsgs.length, 5);

    // Assert correct state transitions sequence
    assert.deepStrictEqual(statusesEmitted, [
      "planning",
      "implementing",
      "reviewing",
      "fixing",
      "reviewing",
      "done"
    ]);
  });

  await t.test("Orchestrator - stops when max rounds is reached without acceptance", async () => {
    const registry = new ProviderRegistry(testConfigPath);
    const runRepo = new RunRepository();
    const messageRepo = new MessageRepository();
    const orchestrator = new Orchestrator(runRepo, messageRepo, registry);

    const runId = "run-test-456";
    const runData: Run = {
      id: runId,
      title: "Test Task 2",
      task: "Test run that will hit max rounds limit",
      status: "created",
      plannerProviderId: "test-planner",
      plannerProviderDisplayName: "Test Planner Provider",
      plannerModel: "model-plan",
      coderProviderId: "test-coder",
      coderProviderDisplayName: "Test Coder Provider",
      coderModel: "model-code",
      maxRounds: 2,
      currentRound: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };

    runRepo.create(runData);

    const statusesEmitted: RunStatus[] = [];
    const eventListener = (event: any) => {
      if (event.type === "status_changed") {
        statusesEmitted.push(event.status);
      }
    };
    eventBus.on(`run:${runId}`, eventListener);
    t.after(() => {
      eventBus.off(`run:${runId}`, eventListener);
    });

    // Mock fetch to always reject review
    globalThis.fetch = async (url: any, options: any) => {
      const body = JSON.parse(options.body);
      const lastMessage = body.messages[body.messages.length - 1]?.content || "";

      if (url.includes("/planner") && lastMessage.includes("User Task:")) {
        return {
          ok: true,
          json: async () => ({ choices: [{ message: { role: "assistant", content: "PLAN: Always fails" } }] })
        } as any;
      }
      if (url.includes("/coder")) {
        return {
          ok: true,
          json: async () => ({ choices: [{ message: { role: "assistant", content: "console.log('bad code');" } }] })
        } as any;
      }
      if (url.includes("/planner") && lastMessage.includes("generated by the Coder")) {
        return {
          ok: true,
          json: async () => ({ choices: [{ message: { role: "assistant", content: "CHANGES_REQUIRED: Still bad!" } }] })
        } as any;
      }
      throw new Error(`Unexpected fetch URL: ${url}`);
    };

    await orchestrator.run(runId);

    const finishedRun = runRepo.getById(runId);
    assert.ok(finishedRun);
    assert.strictEqual(finishedRun.status, "max_rounds_reached");
    assert.strictEqual(finishedRun.currentRound, 2);

    assert.deepStrictEqual(statusesEmitted, [
      "planning",
      "implementing",
      "reviewing",
      "fixing",
      "reviewing",
      "max_rounds_reached"
    ]);
  });
});
