import type { ChatMessage } from "@bridgemind/shared";

export const PLANNER_SYSTEM_PROMPT = `You are the planner and reviewer agent.

Your responsibilities:
- Understand the user's task.
- Create a clear implementation plan.
- Give concrete instructions to the coder model.
- Review the coder model's output.
- Decide whether the output is acceptable.

Rules:
- Do not implement the task yourself unless explicitly asked.
- Do not rewrite the coder's output.
- Give specific, actionable feedback.
- Keep the scope limited to the user's original request.
- If the coder output is acceptable, respond with: FINAL_ACCEPTED.
- If changes are needed, respond with: CHANGES_REQUIRED and list the required fixes.`;

export const CODER_SYSTEM_PROMPT = `You are the coder and implementation agent.

Your responsibilities:
- Follow the planner's instructions.
- Produce concrete implementation output.
- Keep the solution scoped.
- Avoid redesigning the architecture unless the planner explicitly asks for it.
- Do not ignore planner constraints.
- If something is ambiguous, make a reasonable assumption and state it briefly.`;

/**
 * Generates message history for the initial Planning phase of the Planner
 */
export function compilePlanningMessages(task: string): ChatMessage[] {
  return [
    {
      role: "user",
      content: `User Task: ${task}\n\nPlease create a clear implementation plan and instructions for the coder.`
    }
  ];
}

/**
 * Generates message history for the Coder's first attempt
 */
export function compileCoderMessages(task: string, plan: string): ChatMessage[] {
  return [
    {
      role: "user",
      content: `Original User Task: ${task}\n\nHere is the implementation plan and instructions from the Planner:\n${plan}\n\nPlease implement this solution.`
    }
  ];
}

/**
 * Generates message history for the Planner to review the Coder's implementation
 */
export function compileReviewMessages(task: string, plan: string, coderOutput: string): ChatMessage[] {
  return [
    {
      role: "user",
      content: `User Task: ${task}`
    },
    {
      role: "assistant",
      content: plan
    },
    {
      role: "user",
      content: `Here is the implementation generated by the Coder:\n\n${coderOutput}\n\nPlease review this implementation. Decide whether it is acceptable.\nIf acceptable, reply with the exact marker FINAL_ACCEPTED.\nIf improvements are needed, reply with the exact marker CHANGES_REQUIRED followed by a numbered list of fixes.`
    }
  ];
}

/**
 * Generates message history for the Coder to apply fixes requested in a review
 */
export function compileCoderFixMessages(
  task: string, 
  plan: string, 
  previousCoderOutput: string, 
  reviewFeedback: string
): ChatMessage[] {
  return [
    {
      role: "user",
      content: `Original User Task: ${task}\n\nHere is the implementation plan from the Planner:\n${plan}`
    },
    {
      role: "assistant",
      content: previousCoderOutput
    },
    {
      role: "user",
      content: `The Planner reviewed your output and requested the following changes:\n\n${reviewFeedback}\n\nPlease fix the implementation accordingly and return the complete, updated code.`
    }
  ];
}

export function compileContinuationMessages(
  systemPrompt: string,
  history: any[],
  newPrompt?: string
): ChatMessage[] {
  const messages: ChatMessage[] = [];
  
  for (const msg of history) {
    if (msg.role === "user" || msg.role === "system") {
      messages.push({ role: msg.role, content: msg.content });
    } else {
      const prefix = msg.agentRole ? `[Agent: ${msg.agentRole.toUpperCase()}] ` : "";
      messages.push({ role: "assistant", content: `${prefix}${msg.content}` });
    }
  }

  if (newPrompt) {
    messages.push({ role: "user", content: newPrompt });
  }

  return messages;
}

